version: '3'

services:
  stockpred:
    build: .
    volumes:
      - ./models:/app/models
      - ./results:/app/results
      - ./logs:/app/logs
    environment:
      - PYTHONPATH=/app
    ports:
      - "8050:8050"  # For Plotly/Dash visualization
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8050"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    command: python src/dashboard/run.py --host 0.0.0.0 --port 8050 