from setuptools import setup, find_packages

setup(
    name="stockpred",
    version="0.1.0",
    packages=find_packages(),
    install_requires=[
        "numpy",
        "pandas",
        "matplotlib",
        "torch",
        "plotly",
        "gymnasium",
        "ta",
        "yfinance",
        "python-dotenv",
        "dash",
        "dash-bootstrap-components",
        "dash-daq",
        "pytest",
        "pylint",
        "flake8",
        "mypy",
        "black",
        "requests"
    ],
    python_requires=">=3.8",
    author="StockPred Team",
    author_email="author@example.com",
    description="Stock Prediction Tool with RL and Interactive Dashboard",
    long_description=open("README.md").read(),
    long_description_content_type="text/markdown",
    url="https://github.com/yourusername/stockPred",
    classifiers=[
        "Development Status :: 3 - Alpha",
        "Intended Audience :: Financial and Insurance Industry",
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.8",
        "Programming Language :: Python :: 3.9",
        "Programming Language :: Python :: 3.10",
        "License :: OSI Approved :: MIT License",
        "Operating System :: OS Independent",
        "Topic :: Office/Business :: Financial :: Investment",
    ],
)
